### ISSUE TITLE
`contains_key()` is race condition-prone

### ISSUE THREAD

**Issue by njaard** [stusmall/ttl_cache#8]
If you call `contains_key()` in anticipation of calling `get_mut()` (or, preferably, `get()` which doesn't yet exist), then the item may have expired in a short period which means that `get_mut()` will unexpectedly fail. This should be warned for, or even better, remove it entirely and provide a `get()`.

**Comment by stusmall** [comment]
This isn't technically a race condition since these two separate calls aren't one atomic action.  If you want to retrieve a key if it is present just go straight to calling get().  There is no advantage to calling contains_key() first
